//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EThrift_Web.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserTable", Namespace="http://schemas.datacontract.org/2004/07/EThrift_Service")]
    [System.SerializableAttribute()]
    public partial class UserTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.Cart[] CartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.Invoice[] InvoicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RegDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.Review[] ReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.Wishlist[] WishlistsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.Cart[] Carts {
            get {
                return this.CartsField;
            }
            set {
                if ((object.ReferenceEquals(this.CartsField, value) != true)) {
                    this.CartsField = value;
                    this.RaisePropertyChanged("Carts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.Invoice[] Invoices {
            get {
                return this.InvoicesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoicesField, value) != true)) {
                    this.InvoicesField = value;
                    this.RaisePropertyChanged("Invoices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RegDate {
            get {
                return this.RegDateField;
            }
            set {
                if ((this.RegDateField.Equals(value) != true)) {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.Review[] Reviews {
            get {
                return this.ReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewsField, value) != true)) {
                    this.ReviewsField = value;
                    this.RaisePropertyChanged("Reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.Wishlist[] Wishlists {
            get {
                return this.WishlistsField;
            }
            set {
                if ((object.ReferenceEquals(this.WishlistsField, value) != true)) {
                    this.WishlistsField = value;
                    this.RaisePropertyChanged("Wishlists");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cart", Namespace="http://schemas.datacontract.org/2004/07/EThrift_Service")]
    [System.SerializableAttribute()]
    public partial class Cart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.UserTable UserTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartId {
            get {
                return this.CartIdField;
            }
            set {
                if ((this.CartIdField.Equals(value) != true)) {
                    this.CartIdField = value;
                    this.RaisePropertyChanged("CartId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.UserTable UserTable {
            get {
                return this.UserTableField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTableField, value) != true)) {
                    this.UserTableField = value;
                    this.RaisePropertyChanged("UserTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://schemas.datacontract.org/2004/07/EThrift_Service")]
    [System.SerializableAttribute()]
    public partial class Invoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatePlacedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.InvoiceItem[] InvoiceItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.UserTable UserTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatePlaced {
            get {
                return this.DatePlacedField;
            }
            set {
                if ((this.DatePlacedField.Equals(value) != true)) {
                    this.DatePlacedField = value;
                    this.RaisePropertyChanged("DatePlaced");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceId {
            get {
                return this.InvoiceIdField;
            }
            set {
                if ((this.InvoiceIdField.Equals(value) != true)) {
                    this.InvoiceIdField = value;
                    this.RaisePropertyChanged("InvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.InvoiceItem[] InvoiceItems {
            get {
                return this.InvoiceItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceItemsField, value) != true)) {
                    this.InvoiceItemsField = value;
                    this.RaisePropertyChanged("InvoiceItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAmount {
            get {
                return this.TotalAmountField;
            }
            set {
                if ((this.TotalAmountField.Equals(value) != true)) {
                    this.TotalAmountField = value;
                    this.RaisePropertyChanged("TotalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.UserTable UserTable {
            get {
                return this.UserTableField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTableField, value) != true)) {
                    this.UserTableField = value;
                    this.RaisePropertyChanged("UserTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Review", Namespace="http://schemas.datacontract.org/2004/07/EThrift_Service")]
    [System.SerializableAttribute()]
    public partial class Review : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReviewIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.UserTable UserTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReviewId {
            get {
                return this.ReviewIdField;
            }
            set {
                if ((this.ReviewIdField.Equals(value) != true)) {
                    this.ReviewIdField = value;
                    this.RaisePropertyChanged("ReviewId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.UserTable UserTable {
            get {
                return this.UserTableField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTableField, value) != true)) {
                    this.UserTableField = value;
                    this.RaisePropertyChanged("UserTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wishlist", Namespace="http://schemas.datacontract.org/2004/07/EThrift_Service")]
    [System.SerializableAttribute()]
    public partial class Wishlist : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.UserTable UserTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WishlistIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAdded {
            get {
                return this.DateAddedField;
            }
            set {
                if ((this.DateAddedField.Equals(value) != true)) {
                    this.DateAddedField = value;
                    this.RaisePropertyChanged("DateAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.UserTable UserTable {
            get {
                return this.UserTableField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTableField, value) != true)) {
                    this.UserTableField = value;
                    this.RaisePropertyChanged("UserTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WishlistId {
            get {
                return this.WishlistIdField;
            }
            set {
                if ((this.WishlistIdField.Equals(value) != true)) {
                    this.WishlistIdField = value;
                    this.RaisePropertyChanged("WishlistId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/EThrift_Service")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.Cart[] CartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.InvoiceItem[] InvoiceItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.Review[] ReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.Wishlist[] WishlistsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.Cart[] Carts {
            get {
                return this.CartsField;
            }
            set {
                if ((object.ReferenceEquals(this.CartsField, value) != true)) {
                    this.CartsField = value;
                    this.RaisePropertyChanged("Carts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.InvoiceItem[] InvoiceItems {
            get {
                return this.InvoiceItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceItemsField, value) != true)) {
                    this.InvoiceItemsField = value;
                    this.RaisePropertyChanged("InvoiceItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.Review[] Reviews {
            get {
                return this.ReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewsField, value) != true)) {
                    this.ReviewsField = value;
                    this.RaisePropertyChanged("Reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.Wishlist[] Wishlists {
            get {
                return this.WishlistsField;
            }
            set {
                if ((object.ReferenceEquals(this.WishlistsField, value) != true)) {
                    this.WishlistsField = value;
                    this.RaisePropertyChanged("Wishlists");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceItem", Namespace="http://schemas.datacontract.org/2004/07/EThrift_Service")]
    [System.SerializableAttribute()]
    public partial class InvoiceItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.Invoice InvoiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EThrift_Web.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.Invoice Invoice {
            get {
                return this.InvoiceField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceField, value) != true)) {
                    this.InvoiceField = value;
                    this.RaisePropertyChanged("Invoice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceId {
            get {
                return this.InvoiceIdField;
            }
            set {
                if ((this.InvoiceIdField.Equals(value) != true)) {
                    this.InvoiceIdField = value;
                    this.RaisePropertyChanged("InvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EThrift_Web.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartDisplay", Namespace="http://schemas.datacontract.org/2004/07/EThrift_Service")]
    [System.SerializableAttribute()]
    public partial class CartDisplay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartId {
            get {
                return this.CartIdField;
            }
            set {
                if ((this.CartIdField.Equals(value) != true)) {
                    this.CartIdField = value;
                    this.RaisePropertyChanged("CartId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceDisplay", Namespace="http://schemas.datacontract.org/2004/07/EThrift_Service")]
    [System.SerializableAttribute()]
    public partial class InvoiceDisplay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatePlacedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatePlaced {
            get {
                return this.DatePlacedField;
            }
            set {
                if ((this.DatePlacedField.Equals(value) != true)) {
                    this.DatePlacedField = value;
                    this.RaisePropertyChanged("DatePlaced");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceId {
            get {
                return this.InvoiceIdField;
            }
            set {
                if ((this.InvoiceIdField.Equals(value) != true)) {
                    this.InvoiceIdField = value;
                    this.RaisePropertyChanged("InvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAmount {
            get {
                return this.TotalAmountField;
            }
            set {
                if ((this.TotalAmountField.Equals(value) != true)) {
                    this.TotalAmountField = value;
                    this.RaisePropertyChanged("TotalAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReviewDisplay", Namespace="http://schemas.datacontract.org/2004/07/EThrift_Service")]
    [System.SerializableAttribute()]
    public partial class ReviewDisplay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DashboardStats", Namespace="http://schemas.datacontract.org/2004/07/EThrift_Service")]
    [System.SerializableAttribute()]
    public partial class DashboardStats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalOrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalRevenueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalUsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalOrders {
            get {
                return this.TotalOrdersField;
            }
            set {
                if ((this.TotalOrdersField.Equals(value) != true)) {
                    this.TotalOrdersField = value;
                    this.RaisePropertyChanged("TotalOrders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalProducts {
            get {
                return this.TotalProductsField;
            }
            set {
                if ((this.TotalProductsField.Equals(value) != true)) {
                    this.TotalProductsField = value;
                    this.RaisePropertyChanged("TotalProducts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalRevenue {
            get {
                return this.TotalRevenueField;
            }
            set {
                if ((this.TotalRevenueField.Equals(value) != true)) {
                    this.TotalRevenueField = value;
                    this.RaisePropertyChanged("TotalRevenue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalUsers {
            get {
                return this.TotalUsersField;
            }
            set {
                if ((this.TotalUsersField.Equals(value) != true)) {
                    this.TotalUsersField = value;
                    this.RaisePropertyChanged("TotalUsers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        EThrift_Web.ServiceReference1.UserTable Login(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.UserTable> LoginAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        bool RegisterUser(string name, string password, string userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        System.Threading.Tasks.Task<bool> RegisterUserAsync(string name, string password, string userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserExists", ReplyAction="http://tempuri.org/IService1/UserExistsResponse")]
        bool UserExists(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserExists", ReplyAction="http://tempuri.org/IService1/UserExistsResponse")]
        System.Threading.Tasks.Task<bool> UserExistsAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddManager", ReplyAction="http://tempuri.org/IService1/AddManagerResponse")]
        bool AddManager(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddManager", ReplyAction="http://tempuri.org/IService1/AddManagerResponse")]
        System.Threading.Tasks.Task<bool> AddManagerAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllProducts", ReplyAction="http://tempuri.org/IService1/GetAllProductsResponse")]
        EThrift_Web.ServiceReference1.Product[] GetAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllProducts", ReplyAction="http://tempuri.org/IService1/GetAllProductsResponse")]
        System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.Product[]> GetAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProduct", ReplyAction="http://tempuri.org/IService1/GetProductResponse")]
        EThrift_Web.ServiceReference1.Product GetProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProduct", ReplyAction="http://tempuri.org/IService1/GetProductResponse")]
        System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.Product> GetProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductsByCategory", ReplyAction="http://tempuri.org/IService1/GetProductsByCategoryResponse")]
        EThrift_Web.ServiceReference1.Product[] GetProductsByCategory(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductsByCategory", ReplyAction="http://tempuri.org/IService1/GetProductsByCategoryResponse")]
        System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.Product[]> GetProductsByCategoryAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SortProducts", ReplyAction="http://tempuri.org/IService1/SortProductsResponse")]
        EThrift_Web.ServiceReference1.Product[] SortProducts(string sortType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SortProducts", ReplyAction="http://tempuri.org/IService1/SortProductsResponse")]
        System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.Product[]> SortProductsAsync(string sortType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchProducts", ReplyAction="http://tempuri.org/IService1/SearchProductsResponse")]
        EThrift_Web.ServiceReference1.Product[] SearchProducts(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchProducts", ReplyAction="http://tempuri.org/IService1/SearchProductsResponse")]
        System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.Product[]> SearchProductsAsync(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToCart", ReplyAction="http://tempuri.org/IService1/AddToCartResponse")]
        bool AddToCart(int userId, int prodId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToCart", ReplyAction="http://tempuri.org/IService1/AddToCartResponse")]
        System.Threading.Tasks.Task<bool> AddToCartAsync(int userId, int prodId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCartItems", ReplyAction="http://tempuri.org/IService1/GetCartItemsResponse")]
        EThrift_Web.ServiceReference1.CartDisplay[] GetCartItems(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCartItems", ReplyAction="http://tempuri.org/IService1/GetCartItemsResponse")]
        System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.CartDisplay[]> GetCartItemsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCartQuantity", ReplyAction="http://tempuri.org/IService1/UpdateCartQuantityResponse")]
        bool UpdateCartQuantity(int cartId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCartQuantity", ReplyAction="http://tempuri.org/IService1/UpdateCartQuantityResponse")]
        System.Threading.Tasks.Task<bool> UpdateCartQuantityAsync(int cartId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveFromCart", ReplyAction="http://tempuri.org/IService1/RemoveFromCartResponse")]
        bool RemoveFromCart(int userId, int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveFromCart", ReplyAction="http://tempuri.org/IService1/RemoveFromCartResponse")]
        System.Threading.Tasks.Task<bool> RemoveFromCartAsync(int userId, int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCartTotal", ReplyAction="http://tempuri.org/IService1/GetCartTotalResponse")]
        decimal GetCartTotal(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCartTotal", ReplyAction="http://tempuri.org/IService1/GetCartTotalResponse")]
        System.Threading.Tasks.Task<decimal> GetCartTotalAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Checkout", ReplyAction="http://tempuri.org/IService1/CheckoutResponse")]
        bool Checkout(int userId, decimal totalAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Checkout", ReplyAction="http://tempuri.org/IService1/CheckoutResponse")]
        System.Threading.Tasks.Task<bool> CheckoutAsync(int userId, decimal totalAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCart", ReplyAction="http://tempuri.org/IService1/GetCartResponse")]
        EThrift_Web.ServiceReference1.CartDisplay[] GetCart(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCart", ReplyAction="http://tempuri.org/IService1/GetCartResponse")]
        System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.CartDisplay[]> GetCartAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserInvoices", ReplyAction="http://tempuri.org/IService1/GetUserInvoicesResponse")]
        EThrift_Web.ServiceReference1.Invoice[] GetUserInvoices(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserInvoices", ReplyAction="http://tempuri.org/IService1/GetUserInvoicesResponse")]
        System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.Invoice[]> GetUserInvoicesAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoiceDetails", ReplyAction="http://tempuri.org/IService1/GetInvoiceDetailsResponse")]
        EThrift_Web.ServiceReference1.Invoice GetInvoiceDetails(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoiceDetails", ReplyAction="http://tempuri.org/IService1/GetInvoiceDetailsResponse")]
        System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.Invoice> GetInvoiceDetailsAsync(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoiceItems", ReplyAction="http://tempuri.org/IService1/GetInvoiceItemsResponse")]
        EThrift_Web.ServiceReference1.CartDisplay[] GetInvoiceItems(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoiceItems", ReplyAction="http://tempuri.org/IService1/GetInvoiceItemsResponse")]
        System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.CartDisplay[]> GetInvoiceItemsAsync(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllInvoices", ReplyAction="http://tempuri.org/IService1/GetAllInvoicesResponse")]
        EThrift_Web.ServiceReference1.InvoiceDisplay[] GetAllInvoices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllInvoices", ReplyAction="http://tempuri.org/IService1/GetAllInvoicesResponse")]
        System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.InvoiceDisplay[]> GetAllInvoicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoiceHeader", ReplyAction="http://tempuri.org/IService1/GetInvoiceHeaderResponse")]
        EThrift_Web.ServiceReference1.Invoice GetInvoiceHeader(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoiceHeader", ReplyAction="http://tempuri.org/IService1/GetInvoiceHeaderResponse")]
        System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.Invoice> GetInvoiceHeaderAsync(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateInvoiceStatus", ReplyAction="http://tempuri.org/IService1/UpdateInvoiceStatusResponse")]
        bool UpdateInvoiceStatus(int invoiceId, string newStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateInvoiceStatus", ReplyAction="http://tempuri.org/IService1/UpdateInvoiceStatusResponse")]
        System.Threading.Tasks.Task<bool> UpdateInvoiceStatusAsync(int invoiceId, string newStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddReview", ReplyAction="http://tempuri.org/IService1/AddReviewResponse")]
        bool AddReview(int userId, int prodId, int rating, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddReview", ReplyAction="http://tempuri.org/IService1/AddReviewResponse")]
        System.Threading.Tasks.Task<bool> AddReviewAsync(int userId, int prodId, int rating, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductReviews", ReplyAction="http://tempuri.org/IService1/GetProductReviewsResponse")]
        EThrift_Web.ServiceReference1.ReviewDisplay[] GetProductReviews(int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductReviews", ReplyAction="http://tempuri.org/IService1/GetProductReviewsResponse")]
        System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.ReviewDisplay[]> GetProductReviewsAsync(int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HasUserPurchasedItem", ReplyAction="http://tempuri.org/IService1/HasUserPurchasedItemResponse")]
        bool HasUserPurchasedItem(int userId, int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HasUserPurchasedItem", ReplyAction="http://tempuri.org/IService1/HasUserPurchasedItemResponse")]
        System.Threading.Tasks.Task<bool> HasUserPurchasedItemAsync(int userId, int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToWishlist", ReplyAction="http://tempuri.org/IService1/AddToWishlistResponse")]
        bool AddToWishlist(int userId, int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToWishlist", ReplyAction="http://tempuri.org/IService1/AddToWishlistResponse")]
        System.Threading.Tasks.Task<bool> AddToWishlistAsync(int userId, int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWishlist", ReplyAction="http://tempuri.org/IService1/GetWishlistResponse")]
        EThrift_Web.ServiceReference1.CartDisplay[] GetWishlist(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWishlist", ReplyAction="http://tempuri.org/IService1/GetWishlistResponse")]
        System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.CartDisplay[]> GetWishlistAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveFromWishlist", ReplyAction="http://tempuri.org/IService1/RemoveFromWishlistResponse")]
        bool RemoveFromWishlist(int userId, int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveFromWishlist", ReplyAction="http://tempuri.org/IService1/RemoveFromWishlistResponse")]
        System.Threading.Tasks.Task<bool> RemoveFromWishlistAsync(int userId, int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduct", ReplyAction="http://tempuri.org/IService1/AddProductResponse")]
        bool AddProduct(string name, string desc, decimal price, string category, string image, bool active, int stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduct", ReplyAction="http://tempuri.org/IService1/AddProductResponse")]
        System.Threading.Tasks.Task<bool> AddProductAsync(string name, string desc, decimal price, string category, string image, bool active, int stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProduct", ReplyAction="http://tempuri.org/IService1/UpdateProductResponse")]
        bool UpdateProduct(int id, string name, string desc, decimal price, string category, string image, bool active, int stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProduct", ReplyAction="http://tempuri.org/IService1/UpdateProductResponse")]
        System.Threading.Tasks.Task<bool> UpdateProductAsync(int id, string name, string desc, decimal price, string category, string image, bool active, int stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        bool DeleteProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        System.Threading.Tasks.Task<bool> DeleteProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDashboardStats", ReplyAction="http://tempuri.org/IService1/GetDashboardStatsResponse")]
        EThrift_Web.ServiceReference1.DashboardStats GetDashboardStats();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDashboardStats", ReplyAction="http://tempuri.org/IService1/GetDashboardStatsResponse")]
        System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.DashboardStats> GetDashboardStatsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : EThrift_Web.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<EThrift_Web.ServiceReference1.IService1>, EThrift_Web.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EThrift_Web.ServiceReference1.UserTable Login(string name, string password) {
            return base.Channel.Login(name, password);
        }
        
        public System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.UserTable> LoginAsync(string name, string password) {
            return base.Channel.LoginAsync(name, password);
        }
        
        public bool RegisterUser(string name, string password, string userType) {
            return base.Channel.RegisterUser(name, password, userType);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterUserAsync(string name, string password, string userType) {
            return base.Channel.RegisterUserAsync(name, password, userType);
        }
        
        public bool UserExists(string name) {
            return base.Channel.UserExists(name);
        }
        
        public System.Threading.Tasks.Task<bool> UserExistsAsync(string name) {
            return base.Channel.UserExistsAsync(name);
        }
        
        public bool AddManager(string name, string password) {
            return base.Channel.AddManager(name, password);
        }
        
        public System.Threading.Tasks.Task<bool> AddManagerAsync(string name, string password) {
            return base.Channel.AddManagerAsync(name, password);
        }
        
        public EThrift_Web.ServiceReference1.Product[] GetAllProducts() {
            return base.Channel.GetAllProducts();
        }
        
        public System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.Product[]> GetAllProductsAsync() {
            return base.Channel.GetAllProductsAsync();
        }
        
        public EThrift_Web.ServiceReference1.Product GetProduct(int id) {
            return base.Channel.GetProduct(id);
        }
        
        public System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.Product> GetProductAsync(int id) {
            return base.Channel.GetProductAsync(id);
        }
        
        public EThrift_Web.ServiceReference1.Product[] GetProductsByCategory(string category) {
            return base.Channel.GetProductsByCategory(category);
        }
        
        public System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.Product[]> GetProductsByCategoryAsync(string category) {
            return base.Channel.GetProductsByCategoryAsync(category);
        }
        
        public EThrift_Web.ServiceReference1.Product[] SortProducts(string sortType) {
            return base.Channel.SortProducts(sortType);
        }
        
        public System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.Product[]> SortProductsAsync(string sortType) {
            return base.Channel.SortProductsAsync(sortType);
        }
        
        public EThrift_Web.ServiceReference1.Product[] SearchProducts(string query) {
            return base.Channel.SearchProducts(query);
        }
        
        public System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.Product[]> SearchProductsAsync(string query) {
            return base.Channel.SearchProductsAsync(query);
        }
        
        public bool AddToCart(int userId, int prodId, int quantity) {
            return base.Channel.AddToCart(userId, prodId, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> AddToCartAsync(int userId, int prodId, int quantity) {
            return base.Channel.AddToCartAsync(userId, prodId, quantity);
        }
        
        public EThrift_Web.ServiceReference1.CartDisplay[] GetCartItems(int userId) {
            return base.Channel.GetCartItems(userId);
        }
        
        public System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.CartDisplay[]> GetCartItemsAsync(int userId) {
            return base.Channel.GetCartItemsAsync(userId);
        }
        
        public bool UpdateCartQuantity(int cartId, int quantity) {
            return base.Channel.UpdateCartQuantity(cartId, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCartQuantityAsync(int cartId, int quantity) {
            return base.Channel.UpdateCartQuantityAsync(cartId, quantity);
        }
        
        public bool RemoveFromCart(int userId, int prodId) {
            return base.Channel.RemoveFromCart(userId, prodId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveFromCartAsync(int userId, int prodId) {
            return base.Channel.RemoveFromCartAsync(userId, prodId);
        }
        
        public decimal GetCartTotal(int userId) {
            return base.Channel.GetCartTotal(userId);
        }
        
        public System.Threading.Tasks.Task<decimal> GetCartTotalAsync(int userId) {
            return base.Channel.GetCartTotalAsync(userId);
        }
        
        public bool Checkout(int userId, decimal totalAmount) {
            return base.Channel.Checkout(userId, totalAmount);
        }
        
        public System.Threading.Tasks.Task<bool> CheckoutAsync(int userId, decimal totalAmount) {
            return base.Channel.CheckoutAsync(userId, totalAmount);
        }
        
        public EThrift_Web.ServiceReference1.CartDisplay[] GetCart(int userId) {
            return base.Channel.GetCart(userId);
        }
        
        public System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.CartDisplay[]> GetCartAsync(int userId) {
            return base.Channel.GetCartAsync(userId);
        }
        
        public EThrift_Web.ServiceReference1.Invoice[] GetUserInvoices(int userId) {
            return base.Channel.GetUserInvoices(userId);
        }
        
        public System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.Invoice[]> GetUserInvoicesAsync(int userId) {
            return base.Channel.GetUserInvoicesAsync(userId);
        }
        
        public EThrift_Web.ServiceReference1.Invoice GetInvoiceDetails(int invoiceId) {
            return base.Channel.GetInvoiceDetails(invoiceId);
        }
        
        public System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.Invoice> GetInvoiceDetailsAsync(int invoiceId) {
            return base.Channel.GetInvoiceDetailsAsync(invoiceId);
        }
        
        public EThrift_Web.ServiceReference1.CartDisplay[] GetInvoiceItems(int invoiceId) {
            return base.Channel.GetInvoiceItems(invoiceId);
        }
        
        public System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.CartDisplay[]> GetInvoiceItemsAsync(int invoiceId) {
            return base.Channel.GetInvoiceItemsAsync(invoiceId);
        }
        
        public EThrift_Web.ServiceReference1.InvoiceDisplay[] GetAllInvoices() {
            return base.Channel.GetAllInvoices();
        }
        
        public System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.InvoiceDisplay[]> GetAllInvoicesAsync() {
            return base.Channel.GetAllInvoicesAsync();
        }
        
        public EThrift_Web.ServiceReference1.Invoice GetInvoiceHeader(int invoiceId) {
            return base.Channel.GetInvoiceHeader(invoiceId);
        }
        
        public System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.Invoice> GetInvoiceHeaderAsync(int invoiceId) {
            return base.Channel.GetInvoiceHeaderAsync(invoiceId);
        }
        
        public bool UpdateInvoiceStatus(int invoiceId, string newStatus) {
            return base.Channel.UpdateInvoiceStatus(invoiceId, newStatus);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateInvoiceStatusAsync(int invoiceId, string newStatus) {
            return base.Channel.UpdateInvoiceStatusAsync(invoiceId, newStatus);
        }
        
        public bool AddReview(int userId, int prodId, int rating, string comment) {
            return base.Channel.AddReview(userId, prodId, rating, comment);
        }
        
        public System.Threading.Tasks.Task<bool> AddReviewAsync(int userId, int prodId, int rating, string comment) {
            return base.Channel.AddReviewAsync(userId, prodId, rating, comment);
        }
        
        public EThrift_Web.ServiceReference1.ReviewDisplay[] GetProductReviews(int prodId) {
            return base.Channel.GetProductReviews(prodId);
        }
        
        public System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.ReviewDisplay[]> GetProductReviewsAsync(int prodId) {
            return base.Channel.GetProductReviewsAsync(prodId);
        }
        
        public bool HasUserPurchasedItem(int userId, int prodId) {
            return base.Channel.HasUserPurchasedItem(userId, prodId);
        }
        
        public System.Threading.Tasks.Task<bool> HasUserPurchasedItemAsync(int userId, int prodId) {
            return base.Channel.HasUserPurchasedItemAsync(userId, prodId);
        }
        
        public bool AddToWishlist(int userId, int prodId) {
            return base.Channel.AddToWishlist(userId, prodId);
        }
        
        public System.Threading.Tasks.Task<bool> AddToWishlistAsync(int userId, int prodId) {
            return base.Channel.AddToWishlistAsync(userId, prodId);
        }
        
        public EThrift_Web.ServiceReference1.CartDisplay[] GetWishlist(int userId) {
            return base.Channel.GetWishlist(userId);
        }
        
        public System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.CartDisplay[]> GetWishlistAsync(int userId) {
            return base.Channel.GetWishlistAsync(userId);
        }
        
        public bool RemoveFromWishlist(int userId, int prodId) {
            return base.Channel.RemoveFromWishlist(userId, prodId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveFromWishlistAsync(int userId, int prodId) {
            return base.Channel.RemoveFromWishlistAsync(userId, prodId);
        }
        
        public bool AddProduct(string name, string desc, decimal price, string category, string image, bool active, int stock) {
            return base.Channel.AddProduct(name, desc, price, category, image, active, stock);
        }
        
        public System.Threading.Tasks.Task<bool> AddProductAsync(string name, string desc, decimal price, string category, string image, bool active, int stock) {
            return base.Channel.AddProductAsync(name, desc, price, category, image, active, stock);
        }
        
        public bool UpdateProduct(int id, string name, string desc, decimal price, string category, string image, bool active, int stock) {
            return base.Channel.UpdateProduct(id, name, desc, price, category, image, active, stock);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProductAsync(int id, string name, string desc, decimal price, string category, string image, bool active, int stock) {
            return base.Channel.UpdateProductAsync(id, name, desc, price, category, image, active, stock);
        }
        
        public bool DeleteProduct(int id) {
            return base.Channel.DeleteProduct(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProductAsync(int id) {
            return base.Channel.DeleteProductAsync(id);
        }
        
        public EThrift_Web.ServiceReference1.DashboardStats GetDashboardStats() {
            return base.Channel.GetDashboardStats();
        }
        
        public System.Threading.Tasks.Task<EThrift_Web.ServiceReference1.DashboardStats> GetDashboardStatsAsync() {
            return base.Channel.GetDashboardStatsAsync();
        }
    }
}
